import type { NextConfig } from "next";
import path from "path";

const nextConfig: NextConfig = {
  output: 'standalone',
  // Tell Next.js the tracing root is THIS project directory, not the parent
  // workspace root. Without this, Next.js detects the parent rssdeck/
  // package-lock.json and nests standalone output at
  // .next/standalone/.claude/worktrees/<id>/server.js instead of
  // .next/standalone/server.js.
  outputFileTracingRoot: path.resolve(__dirname),
  // Ensure scraper dependencies are included in the standalone bundle.
  // Next.js static analysis misses jsdom and its transitive deps (data files, nested CJS).
  outputFileTracingIncludes: {
    '/api/scrape': [
      './node_modules/@asamuzakjp/css-color/**',
      './node_modules/@asamuzakjp/dom-selector/**',
      './node_modules/@asamuzakjp/nwsapi/**',
      './node_modules/@csstools/color-helpers/**',
      './node_modules/@csstools/css-calc/**',
      './node_modules/@csstools/css-color-parser/**',
      './node_modules/@csstools/css-parser-algorithms/**',
      './node_modules/@csstools/css-syntax-patches-for-csstree/**',
      './node_modules/@csstools/css-tokenizer/**',
      './node_modules/@mozilla/readability/**',
      './node_modules/agent-base/**',
      './node_modules/bidi-js/**',
      './node_modules/css-tree/**',
      './node_modules/cssstyle/**',
      './node_modules/data-urls/**',
      './node_modules/decimal.js/**',
      './node_modules/entities/**',
      './node_modules/html-encoding-sniffer/**',
      './node_modules/http-proxy-agent/**',
      './node_modules/https-proxy-agent/**',
      './node_modules/iconv-lite/**',
      './node_modules/is-potential-custom-element-name/**',
      './node_modules/jsdom/**',
      './node_modules/lru-cache/**',
      './node_modules/mdn-data/**',
      './node_modules/ms/**',
      './node_modules/parse5/**',
      './node_modules/punycode/**',
      './node_modules/require-from-string/**',
      './node_modules/rrweb-cssom/**',
      './node_modules/safer-buffer/**',
      './node_modules/saxes/**',
      './node_modules/source-map-js/**',
      './node_modules/symbol-tree/**',
      './node_modules/tldts/**',
      './node_modules/tldts-core/**',
      './node_modules/tough-cookie/**',
      './node_modules/tr46/**',
      './node_modules/w3c-xmlserializer/**',
      './node_modules/webidl-conversions/**',
      './node_modules/whatwg-encoding/**',
      './node_modules/whatwg-mimetype/**',
      './node_modules/whatwg-url/**',
      './node_modules/ws/**',
      './node_modules/xml-name-validator/**',
      './node_modules/xmlchars/**',
      './node_modules/yallist/**',
    ],
    '/api/tweet': [
      './node_modules/@asamuzakjp/css-color/**',
      './node_modules/@asamuzakjp/dom-selector/**',
      './node_modules/@asamuzakjp/nwsapi/**',
      './node_modules/@csstools/color-helpers/**',
      './node_modules/@csstools/css-calc/**',
      './node_modules/@csstools/css-color-parser/**',
      './node_modules/@csstools/css-parser-algorithms/**',
      './node_modules/@csstools/css-syntax-patches-for-csstree/**',
      './node_modules/@csstools/css-tokenizer/**',
      './node_modules/agent-base/**',
      './node_modules/bidi-js/**',
      './node_modules/css-tree/**',
      './node_modules/cssstyle/**',
      './node_modules/data-urls/**',
      './node_modules/decimal.js/**',
      './node_modules/entities/**',
      './node_modules/html-encoding-sniffer/**',
      './node_modules/http-proxy-agent/**',
      './node_modules/https-proxy-agent/**',
      './node_modules/iconv-lite/**',
      './node_modules/is-potential-custom-element-name/**',
      './node_modules/jsdom/**',
      './node_modules/lru-cache/**',
      './node_modules/mdn-data/**',
      './node_modules/ms/**',
      './node_modules/parse5/**',
      './node_modules/punycode/**',
      './node_modules/require-from-string/**',
      './node_modules/rrweb-cssom/**',
      './node_modules/safer-buffer/**',
      './node_modules/saxes/**',
      './node_modules/source-map-js/**',
      './node_modules/symbol-tree/**',
      './node_modules/tldts/**',
      './node_modules/tldts-core/**',
      './node_modules/tough-cookie/**',
      './node_modules/tr46/**',
      './node_modules/w3c-xmlserializer/**',
      './node_modules/webidl-conversions/**',
      './node_modules/whatwg-encoding/**',
      './node_modules/whatwg-mimetype/**',
      './node_modules/whatwg-url/**',
      './node_modules/ws/**',
      './node_modules/xml-name-validator/**',
      './node_modules/xmlchars/**',
      './node_modules/yallist/**',
    ],
  },
  // Exclude build-time directories that file tracing incorrectly pulls in.
  outputFileTracingExcludes: {
    '*': [
      'dist-electron/**',
      'electron/**',
      '.electron-dist/**',
      'data/**',
      'docs/**',
    ],
  },
};

export default nextConfig;
